// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQeTsFGqs5AgJLtEkemO7zfxZRmKQ0_po',
    appId: '1:302152432080:web:9818a1bb099529673021d5',
    messagingSenderId: '302152432080',
    projectId: 'ecclesia-app',
    authDomain: 'ecclesia-app.firebaseapp.com',
    storageBucket: 'ecclesia-app.firebasestorage.app',
    measurementId: 'G-E29ZGBBPH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCld_lobUNRGcyowLzOXS4PuyDu7QRdNSo',
    appId: '1:302152432080:android:c4bc9db5330eb3b73021d5',
    messagingSenderId: '302152432080',
    projectId: 'ecclesia-app',
    storageBucket: 'ecclesia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15x67Ti_K4-u9wl0eNkcdSl5qdFwk2yI',
    appId: '1:302152432080:ios:f82562fe34a18f503021d5',
    messagingSenderId: '302152432080',
    projectId: 'ecclesia-app',
    storageBucket: 'ecclesia-app.firebasestorage.app',
    iosBundleId: 'com.ecclesia.app',
  );
}
